gluster-server:
        image: elastisys/cloud-glusterfs-server:latest
        privileged: true # needed for Gluster FS
        environment:
         - ROOT_PASSWORD="**ChangeMe**" # Change this, or server won't start
         - GLUSTER_PEERS="1.2.3.4 5.6.7.8" # Set to the trusted pool IP addrs 
         - USE_PUBLIC_IP_ADDRESS="false" # Do as you wish!
        ports:
         - "2222:2222" # SSH_PORT
         - "111:111"
         - "245:245"
         - "443:443"
         - "24007:24007"
         - "2049:2049"
         - "8080:8080"
         - "6010:6010"
         - "6011:6011"
         - "6012:6012"
         - "38465:38465"
         - "38466:38466"
         - "38468:38468"
         - "38469:38469"
         - "49152:49152"
         - "49153:49153"
         - "49154:49154"
         - "49156:49156"
         - "49157:49157"
         - "49158:49158"
         - "49159:49159"
         - "49160:49160"
         - "49161:49161"
         - "49162:49162"
