gluster-server:
        image: elastisys/cloud-glusterfs-server:latest
        privileged: true # needed for Gluster FS
        environment:
         - ROOT_PASSWORD="ChangeThisForTheLoveOfGod"
         - GLUSTER_PEERS="1.2.3.4 5.6.7.8"
         - USE_PUBLIC_IP_ADDRESS="false"
